import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const OutfitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className} h-full antialiased`}
    >

      <body>
        <Navbar />
        <main className="max-w-7xl mx-auto w-11/12 lg:w-full"> {children} </main>
        <Footer />
      </body>

    </html>
  );
}
